"""Version string for `git-curate --version`."""

from __future__ import annotations

from importlib.metadata import version
from pathlib import Path

import sh


def _commit() -> str:
    try:
        from . import _build_info  # type: ignore[attr-defined]  # generated by hatch_build.py
    except ImportError:
        pass
    else:
        return str(_build_info.commit)
    # Editable install or running from the checkout: ask git directly.
    try:
        return str(sh.git("describe", "--always", "--dirty", "--exclude=*", _cwd=Path(__file__).parent)).strip()
    except (sh.ErrorReturnCode, sh.CommandNotFound):
        return "unknown"


def version_string() -> str:
    return f"git-curate {version('git-curate')} ({_commit()})"
